apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80  # Puerto expuesto por el balanceador
      targetPort: 3000  # Puerto del contenedor
